version: "3.8"
services:
  data_subscriber:
    image: suvambasak/subscribe:latest
    env_file:
      - env
    environment:
      - PORT=7777
      - HOST=192.168.0.203
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
