---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for climate control

metadata:
  template_name: ": Service Template for climate control"
  template_author: "Cloud & Smart"
  template_version: "2.0"

imports:
  - relationshiptypes/token_transfer/token_transfer.yaml
  - nodetypes/swarm_leader/swarm_leader.yaml
  - nodetypes/swarm_worker/swarm_worker.yaml
  - nodetypes/docker_services/docker_services.yaml
  - nodetypes/docker_containers/docker_containers.yaml

topology_template:
  inputs:
    outdoor:
      type: string
      description: Input IP address of outdoor node
    
    indoor:
      type: string
      description: Input IP address of indoor node

  node_templates:
    # All fog nodes
    outdoor-node:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: outdoor }
        public_address: { get_input: outdoor }

    indoor-node:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: indoor }
        public_address: { get_input: indoor }

    # Swarm leader node
    docker-swarm-leader:
      type: fog.docker.SwarmLeader
      requirements:
        - host: indoor-node

    # Swarm worker nodes
    docker-swarm-worker:
      type: fog.docker.SwarmWorker
      requirements:
        - host: outdoor-node
        - leader: docker-swarm-leader

    # Docker Service (SWARM)
    broker-service:
      type: fog.docker.Services
      properties:
        name: broker
        url: https://raw.githubusercontent.com/suvambasak/climate-control/main/components/broker/docker-compose.yaml
      requirements:
        - host: docker-swarm-leader
        - dependency: docker-swarm-worker

    # Standalone containers
    sensor-data-publisher:
      type: fog.docker.Containers
      properties:
        name: publisher
        url: https://raw.githubusercontent.com/suvambasak/climate-control/main/components/publish/docker-compose.yaml
      requirements:
        - host: outdoor-node
        - dependency: broker-service

    actuator-data-subscriber:
      type: fog.docker.Containers
      properties:
        name: subscriber
        url: https://raw.githubusercontent.com/suvambasak/climate-control/main/components/subscribe/docker-compose.yaml
      requirements:
        - host: indoor-node
        - dependency: broker-service

  outputs:
    output_worker_token_attribute:
      description: Swarm join token for worker nodes
      value: { get_attribute: [docker-swarm-leader, worker_token] }
    output_manager_token_attribute:
      description: Swarm join token for manager nodes
      value: { get_attribute: [docker-swarm-leader, manager_token] }
    advertised_address:
      description: Swarm join address
      value: { get_attribute: [docker-swarm-leader, advertise_addr] }
